# Generated by Django 3.1.7 on 2021-04-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourguide',
            old_name='france',
            new_name='french',
        ),
        migrations.AlterField(
            model_name='image',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
