# Generated by Django 3.1.7 on 2021-04-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210411_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Tour Images'},
        ),
        migrations.AddField(
            model_name='tour',
            name='hot',
            field=models.BooleanField(default=False),
        ),
    ]
