# Generated by Django 3.1.7 on 2021-04-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20210411_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='visit_places',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.image'),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='gender',
            field=models.CharField(choices=[('1', 'nam'), ('2', 'nữ')], max_length=1, null=True),
        ),
    ]
