# Generated by Django 3.1.7 on 2021-04-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_banner_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='anh',
            new_name='image',
        ),
    ]
