# Generated by Django 3.1.7 on 2021-04-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_auto_20210413_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day1',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day4',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day5',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day6',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day7',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='visit_places',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='tour',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='visit_places',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
