# Generated by Django 3.1.7 on 2021-04-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20210413_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day',
            new_name='activity',
        ),
    ]
