# Generated by Django 3.1.7 on 2021-04-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_auto_20210414_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hot',
        ),
    ]
