# Generated by Django 3.1.7 on 2021-04-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_auto_20210424_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
    ]
