# Generated by Django 3.1.7 on 2021-04-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_remove_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
