# Generated by Django 3.1.7 on 2021-04-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_auto_20210424_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_pay',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
